language: node_js
node_js:
  - '0.10'
  - '0.12'
  - '1'
  - '2'
  - 'iojs'
  - '4'
  - '5'
sudo: false
matrix:
  allow_failures:
    - node_js: 'iojs'
  fast_finish: true
script: npm install . && npm run test-travis
